version: '3.8'
services:
  swiftapirest:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    networks:
      - public
      - private
networks:
  public:
  private: